language: cpp

compiler:
  - clang
  - gcc

before_install:
  - sudo add-apt-repository -y ppa:saiarcot895/chromium-beta
  - sudo apt-get update

install: sudo apt-get install ninja-build

notifications:
  irc:
    channels:
      - "irc.mozilla.org#perf"
    template:
     - "BenWa: %{repository} (%{commit}) : %{message} %{build_url}"
    on_success: change
    on_failure: change

script:
  - $CXX --version
  - ./build.sh
