language: cpp

compiler:
  - clang
  #- gcc

before_install:
  # Ninja
  - sudo add-apt-repository -y ppa:saiarcot895/chromium-beta
  - sudo apt-get update

  # g++4.8.1
  - if [ "$CXX" == "g++" ]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test; fi
  - if [ "$CXX" == "g++" ]; then sudo apt-get update -qq; fi

install:
  - sudo apt-get install ninja-build
  - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq gcc-4.8 g++-4.8 ; fi
  - if [ "$CXX" = "g++" ]; then sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 90; fi

notifications:
  irc:
    channels:
      - "irc.mozilla.org#perf"
    template:
     - "BenWa: %{repository} (%{commit}) : %{message} %{build_url}"
    on_success: change
    on_failure: change

script:
  - $CXX --version
  - ./build.sh
